[package]
edition = "2021"
name = "kafka-mirrormaker"
version = "0.1.0"
authors = ["zsedem"]

[dependencies]
clap = "3.0.0-beta.5"
rdkafka = "0.25"
futures = "*"
tokio = { version = "1.14.0", features = ["full"] }
tokio-stream = { version = "0.1.8", features = ["time"] }
